# Generated by Django 2.0 on 2017-12-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actname', models.CharField(max_length=50, verbose_name='Nom Action')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingname', models.CharField(max_length=150, verbose_name='Non Ingredient')),
                ('ingtype', models.CharField(max_length=2, verbose_name='Type')),
                ('ingnutvalue', models.IntegerField(verbose_name='Valeurs Nutritionnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notcomm', models.CharField(max_length=500, verbose_name='Commentaires')),
                ('notnot', models.IntegerField(verbose_name='Nb Etoiles')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recname', models.CharField(max_length=100, verbose_name='Nom Recettes')),
                ('tempsprep', models.IntegerField(verbose_name='Temps de Préparation')),
                ('tempscuis', models.IntegerField(verbose_name='Temps de Cuisson')),
                ('description', models.CharField(max_length=500)),
                ('recactions', models.ManyToManyField(to='dbservices.Action')),
                ('recing', models.ManyToManyField(to='dbservices.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supername', models.CharField(max_length=50, verbose_name='Non Validateur')),
                ('supertype', models.CharField(max_length=2, verbose_name='Type Validateur')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Non Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utname', models.CharField(max_length=200, verbose_name='Nom Ustensiles')),
                ('utdescr', models.CharField(max_length=500, verbose_name='Description')),
                ('ingspuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.SuperUser')),
                ('utuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.User')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recspuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.SuperUser'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.User'),
        ),
        migrations.AddField(
            model_name='note',
            name='notrec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.Recipe'),
        ),
        migrations.AddField(
            model_name='note',
            name='notspuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.SuperUser'),
        ),
        migrations.AddField(
            model_name='note',
            name='notuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.User'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingspuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.SuperUser'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inguser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.User'),
        ),
        migrations.AddField(
            model_name='action',
            name='actuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.User'),
        ),
        migrations.AddField(
            model_name='action',
            name='actuts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservices.Utensil'),
        ),
    ]
