# Generated by Django 2.0 on 2018-01-13 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('ingtype', 'ingname', 'ingnutvalue')},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingspuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_ingredients', to='dbservices.SuperUser'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='inguser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_ingredients', to=settings.AUTH_USER_MODEL),
        ),
    ]
